markdown: GFM
include:
  - api/classes
  - api/classes/_*
  - api/functions
  - api/functions/_*
  - api/interfaces
  - api/interfaces/_*
  - api/modules
  - api/modules/_*
  - api/types
  - api/types/_*
  - api/variables
  - api/variables/_*
